# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from abelhudo_pkg/Motor_msg.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Motor_msg(genpy.Message):
  _md5sum = "e2b198c4bf4a0862124ad2db607e83d5"
  _type = "abelhudo_pkg/Motor_msg"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint16 pwm
int16 dir
uint16 motor"""
  __slots__ = ['pwm','dir','motor']
  _slot_types = ['uint16','int16','uint16']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       pwm,dir,motor

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Motor_msg, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.pwm is None:
        self.pwm = 0
      if self.dir is None:
        self.dir = 0
      if self.motor is None:
        self.motor = 0
    else:
      self.pwm = 0
      self.dir = 0
      self.motor = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_HhH().pack(_x.pwm, _x.dir, _x.motor))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 6
      (_x.pwm, _x.dir, _x.motor,) = _get_struct_HhH().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_HhH().pack(_x.pwm, _x.dir, _x.motor))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 6
      (_x.pwm, _x.dir, _x.motor,) = _get_struct_HhH().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_HhH = None
def _get_struct_HhH():
    global _struct_HhH
    if _struct_HhH is None:
        _struct_HhH = struct.Struct("<HhH")
    return _struct_HhH
