// Generated by gencpp from file abelhudo_pkg/Encoder_msg.msg
// DO NOT EDIT!


#ifndef ABELHUDO_PKG_MESSAGE_ENCODER_MSG_H
#define ABELHUDO_PKG_MESSAGE_ENCODER_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace abelhudo_pkg
{
template <class ContainerAllocator>
struct Encoder_msg_
{
  typedef Encoder_msg_<ContainerAllocator> Type;

  Encoder_msg_()
    : estado(0)  {
    }
  Encoder_msg_(const ContainerAllocator& _alloc)
    : estado(0)  {
  (void)_alloc;
    }



   typedef uint16_t _estado_type;
  _estado_type estado;





  typedef boost::shared_ptr< ::abelhudo_pkg::Encoder_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::abelhudo_pkg::Encoder_msg_<ContainerAllocator> const> ConstPtr;

}; // struct Encoder_msg_

typedef ::abelhudo_pkg::Encoder_msg_<std::allocator<void> > Encoder_msg;

typedef boost::shared_ptr< ::abelhudo_pkg::Encoder_msg > Encoder_msgPtr;
typedef boost::shared_ptr< ::abelhudo_pkg::Encoder_msg const> Encoder_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::abelhudo_pkg::Encoder_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::abelhudo_pkg::Encoder_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::abelhudo_pkg::Encoder_msg_<ContainerAllocator1> & lhs, const ::abelhudo_pkg::Encoder_msg_<ContainerAllocator2> & rhs)
{
  return lhs.estado == rhs.estado;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::abelhudo_pkg::Encoder_msg_<ContainerAllocator1> & lhs, const ::abelhudo_pkg::Encoder_msg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace abelhudo_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::abelhudo_pkg::Encoder_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::abelhudo_pkg::Encoder_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::abelhudo_pkg::Encoder_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::abelhudo_pkg::Encoder_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::abelhudo_pkg::Encoder_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::abelhudo_pkg::Encoder_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::abelhudo_pkg::Encoder_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e2deebe8d363b67fc8693d7c1c1dea0f";
  }

  static const char* value(const ::abelhudo_pkg::Encoder_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe2deebe8d363b67fULL;
  static const uint64_t static_value2 = 0xc8693d7c1c1dea0fULL;
};

template<class ContainerAllocator>
struct DataType< ::abelhudo_pkg::Encoder_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "abelhudo_pkg/Encoder_msg";
  }

  static const char* value(const ::abelhudo_pkg::Encoder_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::abelhudo_pkg::Encoder_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 estado\n"
;
  }

  static const char* value(const ::abelhudo_pkg::Encoder_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::abelhudo_pkg::Encoder_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.estado);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Encoder_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::abelhudo_pkg::Encoder_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::abelhudo_pkg::Encoder_msg_<ContainerAllocator>& v)
  {
    s << indent << "estado: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.estado);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ABELHUDO_PKG_MESSAGE_ENCODER_MSG_H
