// Generated by gencpp from file abelhudo_pkg/Servo_msg.msg
// DO NOT EDIT!


#ifndef ABELHUDO_PKG_MESSAGE_SERVO_MSG_H
#define ABELHUDO_PKG_MESSAGE_SERVO_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace abelhudo_pkg
{
template <class ContainerAllocator>
struct Servo_msg_
{
  typedef Servo_msg_<ContainerAllocator> Type;

  Servo_msg_()
    : angle(0)  {
    }
  Servo_msg_(const ContainerAllocator& _alloc)
    : angle(0)  {
  (void)_alloc;
    }



   typedef uint16_t _angle_type;
  _angle_type angle;





  typedef boost::shared_ptr< ::abelhudo_pkg::Servo_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::abelhudo_pkg::Servo_msg_<ContainerAllocator> const> ConstPtr;

}; // struct Servo_msg_

typedef ::abelhudo_pkg::Servo_msg_<std::allocator<void> > Servo_msg;

typedef boost::shared_ptr< ::abelhudo_pkg::Servo_msg > Servo_msgPtr;
typedef boost::shared_ptr< ::abelhudo_pkg::Servo_msg const> Servo_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::abelhudo_pkg::Servo_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::abelhudo_pkg::Servo_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::abelhudo_pkg::Servo_msg_<ContainerAllocator1> & lhs, const ::abelhudo_pkg::Servo_msg_<ContainerAllocator2> & rhs)
{
  return lhs.angle == rhs.angle;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::abelhudo_pkg::Servo_msg_<ContainerAllocator1> & lhs, const ::abelhudo_pkg::Servo_msg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace abelhudo_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::abelhudo_pkg::Servo_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::abelhudo_pkg::Servo_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::abelhudo_pkg::Servo_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::abelhudo_pkg::Servo_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::abelhudo_pkg::Servo_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::abelhudo_pkg::Servo_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::abelhudo_pkg::Servo_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ffcccce422d555eeedf1005a7637b109";
  }

  static const char* value(const ::abelhudo_pkg::Servo_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xffcccce422d555eeULL;
  static const uint64_t static_value2 = 0xedf1005a7637b109ULL;
};

template<class ContainerAllocator>
struct DataType< ::abelhudo_pkg::Servo_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "abelhudo_pkg/Servo_msg";
  }

  static const char* value(const ::abelhudo_pkg::Servo_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::abelhudo_pkg::Servo_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 angle\n"
;
  }

  static const char* value(const ::abelhudo_pkg::Servo_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::abelhudo_pkg::Servo_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Servo_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::abelhudo_pkg::Servo_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::abelhudo_pkg::Servo_msg_<ContainerAllocator>& v)
  {
    s << indent << "angle: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ABELHUDO_PKG_MESSAGE_SERVO_MSG_H
